---

- hosts: all
  become: true
  tasks:
  - name: install apache package and add php support
    package:
      name:
        - "{{ apache_package }}" #Apache package variable
        - "{{ php_package }}"
      state: latest
      update_cache: yes
