---
- hosts: all
  become: true
  tasks:
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install apache2 package and add php support for Ubuntu
    tags: apache,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  - name: install apache2 package and add php support for CentOS
    tags: apache,centos
    apt:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  - name: copy default html for site
    tags: apache,copy
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: [db_servers]
  become: true
  tasks:
  - name: install mariadb
    tags: db, centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  - name: install mariadb
    tags: db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: [file_servers]
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest


# ansible-playbook --tags "apache,db" site.yml
